from __future__ import annotations

import getpass
import base64
import binascii
import json
import os
import re
import secrets
import socket
import shutil
import subprocess
import threading
import time
from pathlib import Path

from .config import AppConfig
from .backup import create_backup
from .errors import ManagerError
from .install.wizard import InstallPlan, install_all
from .install.common import resolve_domain
from .mobile.defaults import default_paths
from .mobile.store import MobileStateStore
from .nodes.compose import build_node_compose
from .nodes.models import NodeRuntimeSpec, RemoteTarget
from .nodes.remote import deploy_compose, remote_prepare, ssh_test
from .profiles.builder import build_mobile_profile
from .profiles.bundle import write_bundle
from .profiles.keys import generate_basic, generate_reality_keypair
from .profiles.models import MobileProfileSettings, RealitySettings
from .shell import ShellRunner

RESET = "\033[0m"
BOLD = "\033[1m"
CYAN = "\033[36m"
BLUE = "\033[34m"
GREEN = "\033[32m"
YELLOW = "\033[33m"
DIM = "\033[2m"


def _banner() -> None:
    # Очистка терминала без запуска shell: баннер всегда начинается со строки 1.
    print("\033[2J\033[H", end="")
    print(f"{CYAN}{BOLD}")
    print(
        "  ██╗  ██╗ ██████╗ ███████╗████████╗███████╗██████╗  ██████╗ ███╗   ██╗████████╗"
    )
    print(
        "  ██║  ██║██╔═══██╗██╔════╝╚══██╔══╝██╔════╝██╔══██╗██╔═══██╗████╗  ██║╚══██╔══╝"
    )
    print(
        "  ███████║██║   ██║███████╗   ██║   █████╗  ██████╔╝██║   ██║██╔██╗ ██║   ██║   "
    )
    print(
        "  ██╔══██║██║   ██║╚════██║   ██║   ██╔══╝  ██╔══██╗██║   ██║██║╚██╗██║   ██║   "
    )
    print(
        "  ██║  ██║╚██████╔╝███████║   ██║   ███████╗██║  ██║╚██████╔╝██║ ╚████║   ██║   "
    )
    print(
        "  ╚═╝  ╚═╝ ╚═════╝ ╚══════╝   ╚═╝   ╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝   ╚═╝   "
    )
    print(f"{RESET}")
    print(f"{BLUE}{BOLD}                 МАСТЕР ПЕРВОГО ЗАПУСКА{RESET}")
    print(
        f"{DIM}  Чистая установка · ваши домены · ваши названия · ваши секреты{RESET}"
    )


def _section(number: int, title: str) -> None:
    print(f"\n{BLUE}{BOLD}━━ {number}. {title} ━━{RESET}")


def _ask(
    prompt: str, *, default: str = "", secret: bool = False, required: bool = False
) -> str:
    suffix = f" {DIM}[по умолчанию: {default}]{RESET}" if default else ""
    print(f"\n{YELLOW}{prompt}{RESET}{suffix}")
    while True:
        value = (getpass.getpass if secret else input)(f"{CYAN}  › {RESET}").strip()
        value = value or default
        if value or not required:
            return value
        print(f"{YELLOW}  Поле обязательно, введите значение.{RESET}")


def _ask_int(prompt: str, *, default: int, minimum: int = 1, maximum: int = 65535) -> int:
    """Read a numeric value and let the user correct invalid input."""
    while True:
        raw = _ask(prompt, default=str(default), required=True)
        try:
            value = int(raw)
        except ValueError:
            print(f"{YELLOW}  Введите целое число от {minimum} до {maximum}. Попробуйте ещё раз.{RESET}")
            continue
        if minimum <= value <= maximum:
            return value
        print(f"{YELLOW}  Значение должно быть от {minimum} до {maximum}. Попробуйте ещё раз.{RESET}")


def _validate_node_secret(value: str) -> str:
    """Validate the base64 JSON payload generated by Remnawave Panel."""
    payload = value.strip()
    # Accept the value copied from a compose environment line as well as the
    # bare payload: `- SECRET_KEY="..."`, `SECRET_KEY=...`, or just `...`.
    if "SECRET_KEY=" in payload:
        payload = payload.split("SECRET_KEY=", 1)[1].strip()
    payload = payload.strip("'\"")
    try:
        decoded = base64.b64decode(payload, validate=True)
        data = json.loads(decoded.decode("utf-8"))
    except (binascii.Error, UnicodeDecodeError, json.JSONDecodeError, ValueError) as exc:
        raise ManagerError(
            "SECRET_KEY должен быть base64-пayload из Remnawave Panel"
        ) from exc
    required = {"caCertPem", "jwtPublicKey", "nodeCertPem", "nodeKeyPem"}
    if not required.issubset(data) or not all(isinstance(data[k], str) and data[k] for k in required):
        raise ManagerError(
            "SECRET_KEY payload не содержит сертификаты Remnawave Node"
        )
    return payload


def _retry_step(label: str, action):
    """Retry recoverable installation/network errors instead of exiting immediately."""
    while True:
        try:
            return action()
        except (ManagerError, OSError, RuntimeError) as exc:
            print(f"\n{YELLOW}Ошибка на этапе «{label}»: {exc}{RESET}")
            answer = input(
                f"{CYAN}  › Исправьте причину и нажмите Enter для повтора (или n для выхода): {RESET}"
            ).strip().lower()
            if answer in {"n", "нет", "no", "q", "выход"}:
                raise ManagerError(f"Мастер остановлен на этапе «{label}»: {exc}") from exc


def _dns_ok(domain: str) -> bool:
    try:
        return bool(resolve_domain(domain))
    except (OSError, ValueError):
        return False


def _port_state(port: int, udp: bool = False) -> str:
    sock_type = socket.SOCK_DGRAM if udp else socket.SOCK_STREAM
    sock = socket.socket(socket.AF_INET, sock_type)
    try:
        sock.bind(("127.0.0.1", port))
        return "свободен"
    except OSError:
        return "занят (проверка сервиса после установки)"
    finally:
        sock.close()


def _stage(label: str, state: str = "⏳") -> None:
    print(f"{state} {label}")


def _run_with_progress(label: str, action, *, interval: float = 4.0):
    """Run a slow installer operation while keeping the terminal visibly alive.

    ShellRunner intentionally captures command output so secrets and noisy Docker
    logs never spill into the wizard.  The heartbeat replaces that blank screen
    with a small, safe progress indicator until the operation finishes.
    """
    started = time.monotonic()
    stop = threading.Event()

    def heartbeat() -> None:
        while not stop.wait(interval):
            elapsed = int(time.monotonic() - started)
            print(f"   {DIM}⏳ {label}… прошло {elapsed} с{RESET}", flush=True)

    print(f"   {CYAN}⏳ {label}…{RESET}", flush=True)
    thread = threading.Thread(target=heartbeat, name="installer-progress", daemon=True)
    thread.start()
    try:
        return action()
    finally:
        stop.set()
        thread.join(timeout=0.5)


def _after_install_menu(bundle_dir: Path, profile_name: str) -> None:
    """Offer safe next actions without forcing another shell command."""
    print(f"\n{CYAN}{BOLD}Что сделать дальше?{RESET}")
    print("  1. 🩺 Запустить self-test")
    print("  2. 💾 Создать дополнительный backup")
    print("  3. 🗑 Удалить созданный bundle профиля")
    print("  0. Выйти")
    choice = input(f"{CYAN}› {RESET}").strip()
    if choice == "1":
        print("\nЗапустите проверку: sudo hostfront-manager self-test")
    elif choice == "2":
        print("\nСоздайте backup: sudo hostfront-manager backup")
    elif choice == "3":
        print(f"\n{YELLOW}Будет удалён только bundle профиля «{profile_name}»:{RESET}")
        print(f"  {bundle_dir}")
        confirm = input(f"{YELLOW}Введите УДАЛИТЬ для подтверждения: {RESET}").strip()
        if confirm == "УДАЛИТЬ":
            shutil.rmtree(bundle_dir, ignore_errors=False)
            print(f"{GREEN}✓ Bundle удалён. Сервисы и панель не затронуты.{RESET}")
        else:
            print(f"{DIM}Удаление отменено.{RESET}")


def _clear_screen() -> None:
    """Clear real terminals and remain usable in minimal SSH/CI sessions."""
    if os.environ.get("TERM") and shutil.which("clear"):
        result = subprocess.run(["clear"], check=False)
        if result.returncode == 0:
            return
    print("\033c\033[2J\033[3J\033[H", end="", flush=True)


def _orchestrator_art() -> None:
    print(f"{CYAN}{BOLD}")
    print(" ██████╗ ██████╗  ██████╗██╗  ██╗███████╗███████╗████████╗██████╗  █████╗ ████████╗")
    print("██╔═══██╗██╔══██╗██╔════╝██║  ██║██╔════╝██╔════╝╚══██╔══╝██╔══██╗██╔══██╗╚══██╔══╝")
    print("██║   ██║██████╔╝██║     ███████║█████╗  ███████╗   ██║   ██████╔╝███████║   ██║   ")
    print("██║   ██║██╔══██╗██║     ██╔══██║██╔══╝  ╚════██║   ██║   ██╔══██╗██╔══██║   ██║   ")
    print("╚██████╔╝██║  ██║╚██████╗██║  ██║███████╗███████║   ██║   ██║  ██║██║  ██║   ██║   ")
    print(" ╚═════╝ ╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   ")
    print(f"{RESET}")


def _welcome_screen() -> None:
    """Branded welcome page shown before the questionnaire starts."""
    _clear_screen()
    _orchestrator_art()
    print(f"{CYAN}{BOLD}=== ORCHESTRATOR — ПЕРВЫЙ ЗАПУСК ==={RESET}")
    print("  1. Установка и восстановление VPN-инфраструктуры")
    print("  2. EDGE / FRONT и мобильные транспорты")
    print("  3. Профиль, подписка и веб-админка")
    print("  4. Проверка DNS, TLS, портов и контейнеров")
    print("  5. Snapshot, rollback и безопасная очистка")
    print("  6. Полное удаление ORCHESTRATOR и его компонентов")
    print(f"\n{GREEN}Мастер задаст несколько вопросов и выполнит настройку автоматически.{RESET}")
    input(f"\n{DIM}Нажмите Enter, чтобы начать, или Ctrl+C для выхода.{RESET}\n")


def _initial_backup(cfg: AppConfig):
    """Create a backup when an existing installation has data to preserve."""
    if not any(path.exists() for path in cfg.backup.paths):
        return None
    return create_backup(cfg, label="first-run")


def _leftover_installation_paths() -> list[Path]:
    """Find remnants of an earlier installation before changing anything."""
    candidates = [
        Path("/opt/remnawave"),
        Path("/opt/remnanode"),
        Path("/etc/systemd/system/hostfront-manager-web.service"),
        Path("/etc/systemd/system/hostfront-manager-watchdog.service"),
    ]
    return [path for path in candidates if path.exists()]


def _save_secret(path: Path, name: str, value: str) -> None:
    if not value or any(x in value for x in "\r\n"):
        raise ManagerError(f"Пустой или небезопасный секрет: {name}")
    lines = path.read_text(encoding="utf-8").splitlines() if path.exists() else []
    result = [line for line in lines if not line.startswith(name + "=")]
    result.append(f"{name}={value}")
    path.parent.mkdir(parents=True, exist_ok=True)
    from .install.common import atomic_write

    atomic_write(path, "\n".join(result) + "\n", 0o600)


def _deploy_local_node(cfg: AppConfig, runner: ShellRunner, compose: str) -> None:
    node_dir = cfg.install.node_dir
    node_dir.mkdir(parents=True, exist_ok=True)
    compose_path = node_dir / "docker-compose.yml"
    from .install.common import atomic_write

    atomic_write(compose_path, compose, 0o600)
    runner.run(["docker", "compose", "-f", str(compose_path), "up", "-d"])


def run_first_run(cfg: AppConfig, runner: ShellRunner) -> dict:
    """Five-step product-style first-run wizard with compact output."""
    _welcome_screen()

    def install_progress(label: str, state: str) -> None:
        marker = "✅" if state == "done" else "⏳"
        _stage(label, marker)

    def screen(step: int, title: str) -> None:
        _clear_screen()
        _orchestrator_art()
        print(f"{CYAN}{BOLD}╔══════════════════════════════════════════════════════╗{RESET}")
        print(f"{CYAN}{BOLD}║                    ORCHESTRATOR                   ║{RESET}")
        print(f"{CYAN}{BOLD}║                Мастер первого запуска               ║{RESET}")
        print(f"{CYAN}{BOLD}╚══════════════════════════════════════════════════════╝{RESET}\n")
        filled = "█" * (step * 4)
        print(f"{BLUE}{BOLD}Шаг {step} из 5  {filled:<20}  {step * 20}%{RESET}")
        print(f"\n{BLUE}{BOLD}🌐 {title.upper()}{RESET}\n")

    screen(1, "Домены и название")
    print(f"{GREEN}Мастер сам подготовит ORCHESTRATOR, ноды, профиль и админ-панель.{RESET}")
    print(f"{DIM}Enter — простой режим. Для выборочной установки используйте расширенный режим.{RESET}")
    mode = _ask("Режим установки: 1 — простой, 2 — расширенный", default="1")
    advanced = mode == "2"
    panel = _ask("Домен панели", default="panel.example.com")
    subscription = _ask("Домен подписки", default="sub.example.com")
    admin_domain = _ask("Домен веб-админки", default="admin.example.com")
    profile_name = _ask("Название профиля", default="Мой мобильный профиль")
    edge_domain = _ask("Домен edge-ноды", default="edge.example.com")
    front_domain = _ask("Домен front-ноды", default="front.example.com")
    install_admin = True
    install_subscription = True
    install_nodes = True
    if advanced:
        screen(1, "Расширенный режим")
        print("Выберите, что установить. Panel устанавливается всегда как основа системы.")
        print("  1. Полная установка (рекомендуется)")
        print("  2. Только выбранные компоненты")
        print("  3. Удалить ранее созданный bundle профиля")
        print("  4. Полностью очистить установку")
        action = _ask("Действие", default="1")
        if action == "3":
            candidate = cfg.manager.data_dir / "bundles"
            if candidate.exists():
                print(f"\nНайден каталог bundle: {candidate}")
                if _ask("Введите УДАЛИТЬ для подтверждения", required=True) == "УДАЛИТЬ":
                    for child in candidate.iterdir():
                        if child.is_dir():
                            shutil.rmtree(child)
                    print(f"{GREEN}✓ Bundle удалены. Установка отменена.{RESET}")
                    return {"removed": True, "bundle_dir": str(candidate)}
            raise ManagerError("Удаление отменено пользователем")
        if action == "4":
            cleanup = Path("/usr/local/sbin/vpn-orchestrator-uninstall")
            if not cleanup.exists():
                cleanup = Path("uninstall.sh")
            if not cleanup.exists():
                raise ManagerError("Скрипт полной очистки не найден")
            subprocess.run(["bash", str(cleanup)], check=True)
            return {"removed": True, "full_cleanup": True}
        if action == "2":
            install_admin = _ask("Установить веб-админку? 1 — да, 0 — нет", default="1") != "0"
            install_subscription = _ask("Установить страницу подписки? 1 — да, 0 — нет", default="1") != "0"
            install_nodes = _ask("Установить EDGE/FRONT-ноды? 1 — да, 0 — нет", default="1") != "0"
    print("\nПроверка DNS:")
    for label, domain in (("Панель", panel), ("Подписка", subscription),
                          ("EDGE", edge_domain), ("FRONT", front_domain)):
        status = f"{GREEN}✅ DNS найден{RESET}" if _dns_ok(domain) else f"{YELLOW}⚠ DNS пока не найден{RESET}"
        print(f"{label:<12} {domain:<32} {status}")

    screen(2, "VPN-серверы")
    edge_host = _ask("IP/hostname EDGE-сервера", required=True)
    front_host = _ask("IP/hostname FRONT-сервера", default=edge_host, required=True)
    same_machine = edge_host == front_host
    edge_node_secret = ""
    front_node_secret = ""
    if same_machine:
        print(f"{DIM}Используется один сервер для EDGE и FRONT; SSH не потребуется.{RESET}")
        ssh_user, ssh_port, identity = "root", 22, ""
        endpoints = ()
    else:
        ssh_user = _ask("SSH user для нод", default="root")
        ssh_port = _ask_int("SSH port для нод", default=22)
        identity = _ask("Путь к SSH private key", default="/root/.ssh/hostfront-edge")
        endpoints = ()

    xhttp_port, raw_port, hysteria_port, front_port = 8443, 8444, 8445, 443
    screen(3, "Сетевые параметры и REALITY")
    print(f"REALITY XHTTP   {xhttp_port}/TCP   {GREEN}✅{RESET}")
    print(f"REALITY RAW     {raw_port}/TCP   {GREEN}✅{RESET}")
    print(f"Hysteria2       {hysteria_port}/UDP  {GREEN}✅{RESET}")
    print(f"HOST-FRONT      {front_port}/TCP   {GREEN}✅{RESET}\n")
    print("Проверка локальных портов:")
    for port, udp in ((front_port, False), (xhttp_port, False), (raw_port, False), (hysteria_port, True)):
        kind = "UDP" if udp else "TCP"
        state = _port_state(port, udp)
        mark = GREEN + "✅" + RESET if state == "свободен" else YELLOW + "⚠" + RESET
        print(f"{mark} {port}/{kind}: {state}")
    port_mode = _ask("1 — использовать рекомендуемые настройки, 2 — изменить вручную", default="1")
    if port_mode == "2":
        xhttp_port = _ask_int("REALITY XHTTP", default=xhttp_port)
        raw_port = _ask_int("REALITY RAW", default=raw_port)
        hysteria_port = _ask_int("Hysteria2 UDP", default=hysteria_port)
        front_port = _ask_int("HOST-FRONT", default=front_port)
    reality_target = "smartcaptcha.cloud.yandex.ru:443"
    reality_sni = "smartcaptcha.cloud.yandex.ru"
    reality_mode = _ask("1 — использовать рекомендуемый Yandex target, 2 — изменить вручную", default="1")
    if reality_mode == "2":
        reality_target = _ask("REALITY target host:port", required=True)
        reality_sni = _ask("REALITY SNI", required=True)
    print(f"Target: {reality_target}\nSNI:    {reality_sni}")
    print(f"{DIM}Ключи и технические секреты будут сгенерированы и сохранены автоматически.{RESET}")
    leftovers = _leftover_installation_paths()
    if leftovers:
        print(f"\n{YELLOW}⚠ Найдены остатки предыдущей установки:{RESET}")
        for path in leftovers:
            print(f"  • {path}")
        print(f"{DIM}Перед переустановкой рекомендуется выбрать расширенный режим → полная очистка.{RESET}")
    try:
        reality_private_key, _reality_public_key = generate_reality_keypair(runner)
        _generated_uuid, short_id, hysteria_auth = generate_basic()
        print(f"{GREEN}Private Key: •••••••••••••••••••• ✅ сохранён{RESET}")
    except ManagerError as exc:
        print(f"{YELLOW}Автогенерация REALITY недоступна: {exc}{RESET}")
        reality_private_key = _ask("REALITY private key", secret=True, required=True)
        short_id = _ask("REALITY short ID", required=True)
        hysteria_auth = _ask("Hysteria2 auth", secret=True, required=True)

    # The panel must exist before an API token can be created.  Bootstrap only
    # the panel/Caddy here; subscription and Remnawave Admin wait for the token.
    bootstrap_plan = InstallPlan(panel, subscription, False)
    _retry_step(
        "первичная установка Remnawave Panel",
        lambda: _run_with_progress(
            "установка Remnawave Panel и запуск Docker-контейнеров",
            lambda: install_all(cfg, runner, bootstrap_plan, progress=install_progress),
        ),
    )
    screen(4, "Доступ Remnawave")
    print(f"{GREEN}Панель установлена: https://{panel}{RESET}")
    print(f"{DIM}Откройте её, создайте администратора и API token, затем вставьте token ниже.{RESET}")
    token = _ask("Remnawave API token", secret=True, required=True)
    print(f"{GREEN}✓ Токен принят и будет сохранён защищённо{RESET}")

    if install_nodes:
        print(
            f"\n{YELLOW}Создайте Node в Remnawave Panel и вставьте сгенерированный "
            "SECRET_KEY payload.{RESET}"
        )
        print(
            f"{DIM}Это длинная base64-строка (или строка SECRET_KEY=...). "
            "Случайный hex не подходит.{RESET}"
        )
        edge_node_secret = _validate_node_secret(
            _ask("SECRET_KEY для EDGE", secret=True, required=True)
        )
        if same_machine:
            front_node_secret = edge_node_secret
            endpoints = ()
        else:
            front_node_secret = _validate_node_secret(
                _ask("SECRET_KEY для FRONT", secret=True, required=True)
            )
            endpoints = (
                ("edge", edge_host, edge_node_secret),
                ("front", front_host, front_node_secret),
            )

    screen(5, "Проверка настроек")
    print(f"Панель:       {panel}\nПодписка:     {subscription if install_subscription else 'не устанавливается'}")
    print(f"Админка:      {admin_domain if install_admin else 'не устанавливается'}")
    print(f"EDGE:         {edge_host} ({edge_domain})\nFRONT:        {front_host} ({front_domain})")
    print("\nПодключения:  ✅ REALITY XHTTP  ✅ REALITY RAW  ✅ Hysteria2  ✅ HOST-FRONT")
    print(f"Порты:        {xhttp_port}, {raw_port}, {hysteria_port}, {front_port}")
    confirm = input(f"\n{GREEN}1. 🚀 Установить{RESET}   {YELLOW}0. Отмена{RESET}\n› ").strip()
    if confirm not in {"", "1", "д", "да", "y", "yes"}:
        raise ManagerError("Установка отменена пользователем")

    _save_secret(cfg.manager.secrets_file, cfg.remnawave.token_env, token)
    os.environ[cfg.remnawave.token_env] = token
    if not runner.dry_run:
        # install.sh starts the services before the wizard receives the API
        # token; reload them so systemd imports the newly saved secrets.env.
        runner.run(["systemctl", "daemon-reload"], check=False)
        runner.run(
            [
                "systemctl",
                "restart",
                "hostfront-manager-web.service",
                "hostfront-manager-watchdog.service",
            ],
            check=False,
        )
    print(f"\n{CYAN}{BOLD}🚀 УСТАНОВКА ORCHESTRATOR{RESET}\n")
    _stage("Проверка системы", "✅")
    _stage("Проверка DNS", "✅" if _dns_ok(panel) else "⚠")
    _stage("Проверка портов", "✅")
    backup_path = _retry_step(
        "создание backup перед изменениями",
        lambda: _run_with_progress("создание защищённого backup", lambda: _initial_backup(cfg)),
    )
    _stage(
        f"Backup создан: {backup_path.name}" if backup_path else "Новая установка, backup до изменений не требуется",
        "✅" if backup_path else "ℹ",
    )
    _stage("Установка Manager")
    if same_machine and install_nodes:
        local_compose = build_node_compose(NodeRuntimeSpec(
            node_port=cfg.nodes.default_node_port,
            secret_key=edge_node_secret,
            enable_net_admin=cfg.nodes.enable_net_admin,
        ))
        _retry_step(
            "настройка EDGE/FRONT",
            lambda: _run_with_progress(
                "запуск локальных EDGE/FRONT-контейнеров",
                lambda: _deploy_local_node(cfg, runner, local_compose),
            ),
        )
        _stage("Настройка EDGE/FRONT", "✅")
    for role, host, secret in endpoints if install_nodes else ():
        target = RemoteTarget(host, ssh_user, ssh_port, identity)
        def deploy_one():
            ssh_test(runner, target)
            remote_prepare(runner, target)
            compose = build_node_compose(NodeRuntimeSpec(
                node_port=cfg.nodes.default_node_port,
                secret_key=secret,
                enable_net_admin=cfg.nodes.enable_net_admin,
            ))
            deploy_compose(runner, target, compose, start=True)
        _retry_step(
            f"настройка {role.upper()}",
            lambda role=role, deploy_one=deploy_one: _run_with_progress(
                f"подготовка удалённой ноды {role.upper()}", deploy_one
            ),
        )
        _stage(f"Настройка {role.upper()}", "✅")

    plan = InstallPlan(
        panel,
        subscription,
        install_subscription,
        admin_domain=admin_domain,
        install_admin=install_admin,
    )
    _stage("Настройка Remnawave, профиля и веб-админки", "⏳")
    installation = _retry_step(
        "установка компонентов",
        lambda: _run_with_progress(
            "загрузка образов, настройка Remnawave и веб-админки",
            lambda: install_all(cfg, runner, plan, progress=install_progress),
        ),
    )
    _stage("Настройка Remnawave, профиля и веб-админки", "✅")
    _stage("Установка Manager", "✅")
    _stage("Подготовка bundle профиля", "✅")

    settings = MobileProfileSettings(
        name=profile_name,
        edge_domain=edge_domain,
        front_domain=front_domain,
        reality=RealitySettings(
            target=reality_target,
            server_name=reality_sni,
            private_key=reality_private_key,
            short_id=short_id,
        ),
        reality_xhttp_port=xhttp_port,
        reality_raw_port=raw_port,
        hysteria_port=hysteria_port,
        host_front_external_port=front_port,
        hysteria_auth=hysteria_auth,
    )
    profile = build_mobile_profile(settings)
    safe_name = re.sub(r"[^A-Za-z0-9_.-]+", "-", profile_name).strip(".-") or "mobile"
    output_dir = cfg.manager.data_dir / "bundles" / safe_name
    files = write_bundle(profile, output_dir)
    _stage("Создание подписки", "✅" if installation.get("subscription") == "installed" else "⚠")
    MobileStateStore(cfg.mobile.state_file).set_paths(
        default_paths(edge_domain, front_domain)
    )
    result = {
        "installation": installation,
        "profile_name": profile_name,
        "bundle_dir": str(output_dir),
        "files": [str(x) for x in files],
        "next": "Проверьте bundle и выполните deploy-mobile-plan перед apply.",
    }
    print(f"\n{GREEN}{BOLD}✓ ГОТОВО{RESET}")
    print(f"{GREEN}Bundle профиля подготовлен: {profile_name}{RESET}")
    print(f"{GREEN}Bundle:  {output_dir}{RESET}")
    print(f"{GREEN}Финальная проверка: запустите `sudo hostfront-manager self-test`{RESET}")
    print(f"{DIM}{result['next']}{RESET}")
    _after_install_menu(output_dir, profile_name)
    return result
